### PR TITLE
add google.golang.org/api/photoslibrary/v1 to vendor

### LINKED ISSUE #53: Installation fails due to missing photoslibrary/v1 go package
Installation via `go get -u github.com/nmrshll/gphotos-uploader-cli/cmd/gphotos-uploader-cli` fails with                                                                                                                                                                                                               
```package google.golang.org/api/photoslibrary/v1: cannot find package "google.golang.org/api/photoslibrary/v1"```

Indeed, this package is not in the list if you go to https://godoc.org/google.golang.org/api -- has it been removed?

### PR DESCRIPTION
**Pull request by tonymet**
**NOTE** use `GO111MODULE=off` when building

I've vendored `google.golang.org/api/photoslibrary/xxx`
fixes https://github.com/nmrshll/gphotos-uploader-cli/issues/53

### Building Examples
this package
```
GO111MODULE=off go build lib-gphotos/*.go
GO111MODULE=off go build noserver-gphotos/*.go
```

the main gphotos-uploader-cli
```
cd $GOROOT/src/github.com/nmrshll/gphotos-uploader-cli
GO111MODULE=off go build cmd/gphotos-uploader-cli/main.go
```

### CODE REVIEW

**Comment by tonymet** [comment]
https://github.com/nmrshll/gphotos-uploader-cli/issues/53

please see the build steps above and test

**Comment by jayroh** [comment]
For you: 🏆 

Thank you so much for this @tonymet 🙏 

Finally got this back to working

**Comment by pacoorozco** [comment]
I've tested it, It works like a charm... My only concern is if we should vendor all and use `go mod`. The current approach `mod` + `vendor` is a bit strange to me.

What do you think?

**Comment by tonymet** [comment]
@pacoorozco I just need to work with @nmrshll to go full-mod.  Right now in my testing GO111MODULE=on doesn't work for a couple reasons.  Overall I'm for it--but this PR is to fix the immediate issue until we do

**Comment by tonymet** [comment]
@nmrshll Looks like some good testing. I'll self-merge later today if that's ok

**Comment by tonymet** [comment]
@nhorvath could i get your help merging?

**Comment by tonymet** [comment]
@nhorvath @pacoorozco  Hi guys I have a few pull requests out that I think would be a help.  What would be the best way to help get those merged?

**Comment by nhorvath** [comment]
@tonymet I'm not really a go developer, but i helped with some early functionality for large photo libraries which is why i'm here. Sorry, but I don't know what this PR does so I will have to deffer to someone else.

**Comment by pacoorozco** [comment]
Fixed on https://github.com/gphotosuploader/google-photos-api-client-go

**Pull request closed without merging**
